name: CI/CD for Laravel

on:
  push:
    branches:
      - main
      - gitlabCICD
  pull_request:
    branches:
      - main
      - gitlabCICD

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, exif, bcmath, gd, pdo, mysqli
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Set up .env file
        run: cp .env.example .env

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      # Run Laravel tests
      - name: Run PHPUnit tests
        run: php artisan test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/gitlabCICD'

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Fix permissions
        run: |
            sudo chown -R www-data:www-data /var/www/laravel/storage /var/www/laravel/bootstrap/cache
            sudo chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache

      # Sync code to server
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/laravel
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart php8.4-fpm
            sudo systemctl restart nginx
